language: swift
osx_image: xcode11.3
xcode_workspace: station.xcworkspace
xcode_scheme: station
script:
  - xcodebuild clean build -sdk iphonesimulator -workspace station.xcworkspace -scheme station CODE_SIGNING_REQUIRED=NO | xcpretty
branches:
  only:
  - master
before_install:
  - rvm use system
